### ISSUE TITLE
Download corrupts the response content

### ISSUE THREAD

**Issue by stevechilds** [ConvertAPI/convertapi-php#12]
When you download a file via the Client::download method CURL dumps the content of the file into the php output buffer, which then gets sent ahead of any response from the PHP script.

e.g. We're using ConvertAPI to convert a file to Pdf when its uploaded via an AJAX request. We found that the ajax call was returning a dump of the PDF file ahead of the JSON we were expecting. Adding a single line into client.php fixed it.

I've created a pull request to address this issue. #11

**Comment by stevechilds** [comment]
Actually, disregard this. It was actually because the $fp handle failed to create due to permissions, but because this isn't checked in your code, CURL simply echos the file content. You may want to add a check after the $fp = fopen($path, 'wb'); line.

**Comment by laurynas-baltsoft** [comment]
Thank you for the report, fixed in version `v1.1.1`:
https://github.com/ConvertAPI/convertapi-php/commit/51acbd0df52d4fa9b8991decf186e6485401455f
