### ISSUE TITLE
Conversion problem in Laravel Queue

### ISSUE THREAD

**Issue by LouisCharles70** [ConvertAPI/convertapi-php#14]
When I am running conversions in a Queue I get the following error :

`ConvertApi\Error\Client: SSL certificate problem: unable to get local issuer certificate in C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\Client.php:119 Stack trace: #0 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\Client.php(103): ConvertApi\Client->handleCurlError(Resource id #902) #1 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\Client.php(44): ConvertApi\Client->execute(Resource id #902) #2 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\FileUpload.php(31): ConvertApi\Client->upload('C:\\laragon\\www\\...', '2019-11-29-troy...') #3 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\FileUpload.php(25): ConvertApi\FileUpload->result() #4 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\FormatDetector.php(15): ConvertApi\FileUpload->getFileExt() #5 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\Task.php(86): ConvertApi\FormatDetector->run() #6 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\Task.php(27): ConvertApi\Task->detectFormat(Array) #7 C:\laragon\www\webapp_adminLTE\vendor\convertapi\convertapi-php\lib\ConvertApi\ConvertApi.php(74): ConvertApi\Task->run() #8 C:\laragon\www\webapp_adminLTE\app\Http\Controllers\MenusController.php(611): ConvertApi\ConvertApi::convert('pdf', Array) #9 C:\laragon\www\webapp_adminLTE\app\Jobs\SendMenus.php(43): App\Http\Controllers\MenusController->convertMenuToPDF('C:\\laragon\\www\\...') #10 [internal function]: App\Jobs\SendMenus->handle() #11 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array(Array, Array) #12 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\Util.php(34): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #13 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #14 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #15 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #16 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(94): Illuminate\Container\Container->call(Array) #17 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendMenus)) #18 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendMenus)) #19 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #20 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendMenus), false) #21 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\SendMenus)) #22 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendMenus)) #23 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #24 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(App\Jobs\SendMenus)) #25 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(88): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #26 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(348): Illuminate\Queue\Jobs\Job->fire() #27 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(294): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions)) #28 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Worker.php(129): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions)) #29 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(112): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions)) #30 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Queue\Console\WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default') #31 [internal function]: Illuminate\Queue\Console\WorkCommand->handle() #32 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(32): call_user_func_array(Array, Array) #33 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\Util.php(34): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #34 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure(Object(Closure)) #35 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #36 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Container\Container.php(590): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #37 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Console\Command.php(202): Illuminate\Container\Container->call(Array) #38 C:\laragon\www\webapp_adminLTE\vendor\symfony\console\Command\Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #39 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Console\Command.php(189): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #40 C:\laragon\www\webapp_adminLTE\vendor\symfony\console\Application.php(934): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #41 C:\laragon\www\webapp_adminLTE\vendor\symfony\console\Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #42 C:\laragon\www\webapp_adminLTE\vendor\symfony\console\Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #43 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Console\Application.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #44 C:\laragon\www\webapp_adminLTE\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(131): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #45 C:\laragon\www\webapp_adminLTE\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #46 {main}
--`

This is the conversion method from my controller : 

`<?php

namespace App\Http\Controllers;

use App\Dish;
use App\Ingredient;
use App\MealPlan;
use App\MealPlanItemCategory;
use App\Menu;
use App\NutritionalValue;
use Illuminate\Bus\Queueable;
use Illuminate\Http\Request;
use DB;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Artisan;
use PhpOffice\PhpSpreadsheet\Calculation\Category;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Illuminate\Support\Facades\Mail;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;

use Illuminate\Contracts\Queue\ShouldQueue;

use \ConvertApi\ConvertApi;

class MenusController extends Controller
{

    public function convertMenuToPDF($file){
        $result = ConvertApi::convert('pdf', ['File' => $file]);
        # save to file
        $pdf = str_replace('docx','pdf',$file);

        $result->getFile()->save($pdf);

        return $pdf;
    }
}`

And this is my Job : 

`<?php

namespace App\Jobs;

use App\Http\Controllers\MenusController;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Mail;

class SendMenus implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $menu,$when;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($menu,$when)
    {
        $this->menu = $menu;
        $this->when = $when;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle(MenusController $menusController)
    {
        $menuFile = $menusController->templateEdition($this->menu->id);

        $menu = $this->menu;
        $when = $this->when;
        $pdfFile = $menusController->convertMenuToPDF($menuFile);

    }
}`

**Comment by JonasJasas** [comment]
Hello,

please check ssl certificates CA if they are present. Try https request
with PHP to any other server to verify.
