### ISSUE TITLE
how to solve the Connection timed out issue while converting a large file.

### ISSUE THREAD

**Issue by Rajasegar4497** [ConvertAPI/convertapi-php#15]
Fatal error: Method ConvertApi\FileUpload::__toString() must not throw an exception, caught ConvertApi\Error\Client: Connection timed out after 5001 milliseconds in /opt/www/asic/brokerage/brokerage_dragdrop_v2/pdfconversion_v3/lib/ConvertApi/Client.php on line 19

**Comment by Saketsuraj** [comment]
@Rajasegar4497 , Did you find any solution? I am facing the same issue

**Comment by laurynas-baltsoft** [comment]
I think you are facing network issue - because connect timeout error is raised. Default connect timeout is 5s:
https://github.com/ConvertAPI/convertapi-php/blob/master/lib/ConvertApi/ConvertApi.php#L22

You can adjust it by changing `ConvertApi::$connectTimeout` value.
