### ISSUE TITLE
ConvertApi::convert is showing Fatal error. Method ConvertApi\FileUpload::__toString() must not throw an exception  

### ISSUE THREAD

**Issue by euginepj** [ConvertAPI/convertapi-php#16]
Each time it is ending up in a fatal error. 

**Fatal error:** Method ConvertApi\FileUpload::__toString() must not throw an exception, caught ConvertApi\Error\Api: Code **lib\ConvertApi\FileParam.php** on line 12 

While tracking down the error, I reached `Client.php` file, `function execute($ch)` where `curl_exec($ch)` is returning `400 Bad Request`. 

Please help me to get the result. 

This is my code 
```
require __DIR__ . '/lib/ConvertApi/autoload.php';
use \ConvertApi\ConvertApi;
ConvertApi::setApiSecret('<THIS IS SECRET>');
$dir = sys_get_temp_dir();

$upload = new \ConvertApi\FileUpload('files/pdf.pdf');
$result = ConvertApi::convert('tc', ['File' => $upload]);
$savedFile = $result->saveFiles($dir);
```

Please let me know what can be done from my side.

**Comment by laurynas-baltsoft** [comment]
Target format `tc` is not valid, you can find valid conversion formats here:
https://www.convertapi.com/conversions

Also there is no need to instantiate `FileUpload` separately if you will do only one conversion with from the file. You can just call convert with the file path, like this:

```php
require __DIR__ . '/lib/ConvertApi/autoload.php';
use \ConvertApi\ConvertApi;
ConvertApi::setApiSecret('<THIS IS SECRET>');
$dir = sys_get_temp_dir();

$result = ConvertApi::convert('jpg', ['File' => 'files/pdf.pdf']);
$savedFile = $result->saveFiles($dir);
```

More detailed example:
https://github.com/ConvertAPI/convertapi-php/blob/master/examples/create_pdf_thumbnail.php#L18
