### ISSUE TITLE
Introduce alternative converter parameter in conversion method

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-php#18]
The same as in Ruby lib https://github.com/ConvertAPI/convertapi-ruby/issues/10

**Comment by laurynas-baltsoft** [comment]
Implemented in version `v1.2.1`

**Comment by tomasr78** [comment]
The alternative converter is not working, how URL is built?


The URL should look like this using example below

`https://v2.convertapi.com/convert/docx/to/pdf/converter/openoffice`

One of our users complains that if he set converter it is still ignored. 

```
<?php
require __DIR__ . '/../lib/ConvertApi/autoload.php';

use \ConvertApi\ConvertApi;

# set your api secret
ConvertApi::setApiSecret(getenv('CONVERT_API_SECRET'));

# Example of saving Word docx to PDF using OpenOffice converter
# https://www.convertapi.com/doc-to-pdf/openoffice

$dir = sys_get_temp_dir();
$upload = new \ConvertApi\FileUpload('files/test.docx');

$result = ConvertApi::convert('pdf', ['File' => $upload, 'converter' => 'openoffice']);
$savedFiles = $result->saveFiles($dir);

echo "The PDF saved to:\n";
print_r($savedFiles);

```

**Comment by felixprawira** [comment]
found the issue, the parameter converter must be in lowercase, while the other parameters can be in first letter uppercase
![image](https://user-images.githubusercontent.com/7145915/151207797-9401c45a-9f34-4219-a775-5974bec7befc.png)

**Comment by kostas-baltsoft** [comment]
@laurynas-baltsoft customers are complaining about this issue. We need to convert the ```$params['converter']``` to lowercase before appending it to the URL. I cannot see a commit referenced to this issue. Is this fixed already?

**Comment by tomasr78** [comment]
@laurynas-baltsoft @kostas-baltsoft I think the problem is not how the library appends parameters in lower or uppercase but how it compares. The all-string comparison should be Case-Insensitive and not Case-Sensitive like now.
