### ISSUE TITLE
Error while merging two PDF files

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-php#2]
Conversion:

`$result = ConvertApi::convert('merge', [
        'Files[0]' => new \ConvertApi\FileUpload('files/test.pdf'),
        'Files[1]' => new \ConvertApi\FileUpload('files/test.pdf'),
    ], 'pdf'
);

$result->saveFiles('/tmp');`

Error:
`PHP Catchable fatal error:  Method ConvertApi\FileUpload::__toString() must return a string value in convertapi-php/lib/ConvertApi/Client.php on line 19`

**Comment by laurynas** [comment]
It should be:

```php
$files = [
  new \ConvertApi\FileUpload('files/test.pdf'), 
  new \ConvertApi\FileUpload('files/test.pdf')
];

$result = ConvertApi::convert('merge', ['Files' => $files], 'pdf');
```

or even simplier:

```php
$files = [
  'files/test.pdf', 
  'files/test.pdf'
];

$result = ConvertApi::convert('merge', ['Files' => $files], 'pdf');
```

**Comment by laurynas-baltsoft** [comment]
It should be:

```php
$files = [
  new \ConvertApi\FileUpload('files/test.pdf'), 
  new \ConvertApi\FileUpload('files/test.pdf')
];

$result = ConvertApi::convert('merge', ['Files' => $files], 'pdf');
$result->saveFiles('/tmp');
```

or even simplier:

```php
$files = [
  'files/test.pdf', 
  'files/test.pdf'
];

$result = ConvertApi::convert('merge', ['Files' => $files], 'pdf');
$result->saveFiles('/tmp');
```

**Comment by JonasJasas** [comment]
Snippets simplified and tested, works fine
