### ISSUE TITLE
Failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-php#22]
The problem consists of two cases:

1. The PHP library lacks a method to get file content as a stream, I only find the `Save `method to file system: https://github.com/ConvertAPI/convertapi-php/blob/416bc8ec852dc101c4988e85adab3b45e422e407/lib/ConvertApi/ResultFile.php#L41

2. Due to the lack of a method to get file stream developers using the `file_get_contents` method to read files from URL as a stream.

The problem:

We have depreciated the HTTP/1.0 version for internal technical reasons and `file_get_contents` started throwing exceptions:

` failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required` 

To fix this issue we need to set HTTP version using context:

```
$context = stream_context_create(array('http'=>array('protocol_version'=>'1.1')));
file_get_contents('http://ip:port/?light=on', false, $context);
```
See also the full list of context options http://www.php.net/manual/en/context.http.php

Suggested solution:

1. Add the `save to stream` method to the library.

2. Switch automatically to HTTP 1.1. version when Library is used to prevent an error if a developer still decides to use the `file_get_contents` method. I am not certain if that possible to switch the HTTP version globally in PHP.

**Comment by laurynas-baltsoft** [comment]
Added `getContents` method and updated example:
https://github.com/ConvertAPI/convertapi-php/blob/master/README.md#file-conversion

Released 1.5.0 version.
