### ISSUE TITLE
PowerPoint conversions fail if any elements use transparency

### ISSUE THREAD

**Issue by HenryHall** [ConvertAPI/convertapi-php#23]
The conversion process will end abruptly when converting PowerPoint slides with transparency.

For example:  If a 5 page PowerPoint uses transparency on page 3 only, ConvertAPI will return 3 images instead of the expected 5, and the 3rd image will be corrupt.  No errors are thrown.

**Comment by tomasr78** [comment]
Could you share the PowerPoint file for testing?

**Comment by HenryHall** [comment]
It appears that this issue has been resolved.  Thanks!
