### ISSUE TITLE
Spaces in filenames become +'s

### ISSUE THREAD

**Issue by dsuurlant** [ConvertAPI/convertapi-php#26]
The PHP client uses cURL under the hood, which converts filenames with spaces in them to have `+`es instead. 

As a result of this, Word and Excel files that have the `FILENAME` special property (when using the 'Direct' converter) will have the filename with spaces in them, i.e. `AC+1+report+template.docx`. It's the same for the API request logs.

This is related to a series of support requests to `support@convertapi.com`, so please refer there for more information and file examples.

**Comment by tomasr78** [comment]
It could be related to our file server and not a library, we are verifying this and post an update soon.

**Comment by tomasr78** [comment]
@dsuurlant Could you test now? I think we have fixed it.

**Comment by dsuurlant** [comment]
I've tested this, unfortunately the filename still ends up having +'s. (I can also review this in my conversion statistics, not just the FILENAME property)

**Comment by dsuurlant** [comment]
Has there been any progress on fixing this issue?

**Comment by dsuurlant** [comment]
I'd like to know if there was any progress on fixing this issue!

**Comment by tomasr78** [comment]
@laurynas-baltsoft could you look at this? I am not sure if this is related to the PHP library or the API itself.

**Comment by dsuurlant** [comment]
Has there been any progress regarding this issue? If there is any more information we can provide, please let us know.

**Comment by laurynas-baltsoft** [comment]
Fixed in release v1.6.0:
https://github.com/ConvertAPI/convertapi-php/releases/tag/v1.6.0
