### ISSUE TITLE
Handle non-json errors

### ISSUE THREAD

**Issue by gufoe** [ConvertAPI/convertapi-php#29]
Hello, I am getting the following error:
`TypeError Cannot access offset of type string on string`
from the file:
`lib/ConvertApi/Client.php:156`

This is because the server returns a non-json string.
This case should throw an Error\Api just like a json-error.
Just add this before using the $json as an array, on line 156:
`if (is_string($json)) throw new Error\Api($json);`

**Comment by laurynas-baltsoft** [comment]
Fixed in release v1.6.0
https://github.com/ConvertAPI/convertapi-php/releases/tag/v1.6.0
