### ISSUE TITLE
Missing documentation on conversion parameters?

### ISSUE THREAD

**Issue by pandemonia** [ConvertAPI/convertapi-php#38]
I am trying to find the details for all the conversion parameters. The README file under [Additional conversion parameters](https://github.com/ConvertAPI/convertapi-php#additional-conversion-parameters) includes the line "_All conversion parameters and explanations can be found [here](https://www.convertapi.com/)._" but I do not find any list of supported parameters on the website either.

Can you please help me find this documentation?

**Comment by tomasr78** [comment]
You can find them at https://www.convertapi.com/conversions

**Comment by teamiecareers** [comment]
Got it, thanks!

**Comment by pandemonia** [comment]
Got it, thanks!
