### ISSUE TITLE
Update this library to support the undocumented changes in the API.

### ISSUE THREAD

**Issue by eric-addcream** [ConvertAPI/convertapi-php#39]
Convertapi made breaking changes to the API without notification, and now this library is out of date.
Instead of sending a parameter for async, the api now requires a new URL instead.
https://www.convertapi.com/doc/async

This library does not support this and any application that relies on this library for async requests is now broken.

**Comment by JonasJasas** [comment]
The client library was not designed to be used with the async API feature. If the async feature is used, HTTP requests must be called using the native HTTP client:
```php
$curl = curl_init();
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_BINARYTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Accept: application/json'));
curl_setopt($curl, CURLOPT_URL, "https://v2.convertapi.com/async/convert/docx/to/pdf?secret=".$secret);
curl_setopt($curl, CURLOPT_POSTFIELDS, array('file' => new CurlFile($file_path)), 'storefile' => 'false');
$result = curl_exec($curl);
if (curl_getinfo($curl, CURLINFO_HTTP_CODE) == 200) {
     $job_id = json_decode($result)->JobId;
} else {
    print("Server returned error:\n".$result."\n");
    exit;
}
```
