### ISSUE TITLE
report the convert api not working

### ISSUE THREAD

**Issue by Musharafullah** [ConvertAPI/convertapi-php#42]
I am using the API pdf to jpg but the API returns null from your side. and I already talked about this issue with convertapi supporting team but they say it is still an issue in the PHP library and do report it here please fix this issue ASAP because our project totally depends on your API response. thanks
![image](https://user-images.githubusercontent.com/35028956/236398030-98d32593-e8b7-47d2-b358-66825ede7655.png)
my code-----------
<?php

namespace App\Http\Controllers;

use ConvertApi\ConvertApi;
use ConvertApi\Error\ApiError;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\HttpFoundation\Response;

class ConvertController extends Controller
{
    public function convertPdfToImage(Request $request)
    {
        try {
            // Validate the request data
            $validator = Validator::make($request->all(), [
                'pdf' => 'required|file|mimes:pdf|max:2048', // Adjust the maximum file size as needed
            ]);

            // Check if the validation fails
            if ($validator->fails()) {
                $errorMessage = $validator->errors()->first();
                return response()->json(['error' => $errorMessage], Response::HTTP_NOT_FOUND);
            }

            // Set your ConvertAPI.com API secret key
            ConvertApi::setApiSecret('R13KzvjgO2EGTY86');

            // Retrieve the uploaded PDF file
            $pdfFile = $request->file('pdf');
            if (!$pdfFile instanceof UploadedFile) {
                return response()->json(['error' => 'PDF file not found.'], Response::HTTP_NOT_FOUND);
            }

            // Specify the desired image format
            $imageFormat = 'jpg'; // Change it to your preferred image format

            // Convert the PDF to an image
            $result = ConvertApi::convert('pdf', [
                'File' => $pdfFile->path(),
            ], $imageFormat);

            // Get the converted image data as a string
            $imageData = $result->getFileData();

            // Set the appropriate headers for the image response
            $headers = [
                'Content-Type' => 'image/' . $imageFormat,
                'Content-Disposition' => 'inline; filename="converted_image.' . $imageFormat . '"',
            ];

            // Return the image response
            return response($imageData, Response::HTTP_OK, $headers);
        } catch (ApiError $e) {
            // Log the error
            Log::error('ConvertAPI Error: ' . $e->getMessage());

            // Return an error response
            return response()->json(['error' => 'An error occurred during the conversion process.'], Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}

**Comment by tomasr78** [comment]
The issue already fixed in new release.
