### ISSUE TITLE
All classes use dynamic properties

### ISSUE THREAD

**Issue by editorassistant** [ConvertAPI/convertapi-php#46]
Dynamic properties are deprecated and generate errors in 8.2.x already.

**Comment by tomasr78** [comment]
related https://github.com/ConvertAPI/convertapi-php/issues/48

**Comment by tomasr78** [comment]
@laurynas-baltsoft, Can you look at this issue and update the PHP library if needed?

**Comment by laurynas-baltsoft** [comment]
Fixed in 2.0.0 version:
https://github.com/ConvertAPI/convertapi-php/releases/tag/v2.0.0
