### ISSUE TITLE
Getting Issue

### ISSUE THREAD

**Issue by webexpertesfera** [ConvertAPI/convertapi-php#48]
Hi Support Team,

As I discussed with your support team member Jonas I'm generating ticket for the issue with API. Please check the attachment for the  errors.
website URL: https://typetester.dk/

After filling the forms at the last on result page I'm getting error.It was working properly before but suddenly I'm getting the errors.

Here is the code I'm using:

 <?php

        ob_start();
require_once '/var/www/typetester.dk/public_html/vendor/autoload.php';
$res = new \ConvertApi\ConvertApi;

if($lang == 'english'){
$template_path = get_template_directory() . '/index-eng.html';
}else
{
$template_path = get_template_directory() . '/index-danish.html';
}

$template = file_get_contents($template_path);
$template = str_replace('{NAME}', $name, $template);
$template = str_replace('{EMAIL}', $email, $template);
$template = str_replace('{DATE}', date('d-m-y'), $template);

if($lang == 'english'){
$template = str_replace('{SCORE1}', $trait_sums['Emotional stability'], $template);
$template = str_replace('{SCORE2}', $trait_sums['Openness'], $template);
$template = str_replace('{SCORE3}', $trait_sums['Extraversion'], $template);
$template = str_replace('{SCORE4}', $trait_sums['Conscientiousness'], $template);
$template = str_replace('{SCORE5}', $trait_sums['Agreeableness'], $template);
}else{
$template = str_replace('{SCORE1}', $trait_sums['Følelsesmæssig stabilitet'], $template);
$template = str_replace('{SCORE2}', $trait_sums['Åbenhed'], $template);
$template = str_replace('{SCORE3}', $trait_sums['Udadvendthed'], $template);
$template = str_replace('{SCORE4}', $trait_sums['Samvittighedsfuldhed'], $template);
$template = str_replace('{SCORE5}', $trait_sums['Imødekommenhed'], $template);
}

if($lang == 'english'){
$fp = fopen(get_template_directory().'/eng.html', 'w');  
fwrite($fp, $template);  
fclose($fp);  
}else
{
$fp = fopen(get_template_directory().'/danish.html', 'w');  
fwrite($fp, $template);  
fclose($fp);  

}

if($lang == 'english'){
$template_path1 = get_template_directory() . '/eng.html';
}else
{
$template_path1 = get_template_directory() . '/danish.html';
}

$res->setApiSecret('XXXXXXXX');
$result = $res->convert('pdf', [
       'File' => $template_path1,
        'BreakAfterElements' => 'section',
   ], 'html'
);
$pdf_path = get_template_directory();
$result->saveFiles($pdf_path);

if($lang == 'english'){
$pdf_path = get_template_directory() . '/Personality test results.pdf';
}else
{
$pdf_path = get_template_directory() . '/Personlighedstest resultater.pdf';
}

$to = $email;
if($lang == 'english'){
$subject = 'Personality Test result';
$body = 'Find your personality result in attachment';
}else{
$subject = 'Personlighedstest resultat';
$body = ' Tak fordi du tog vores personlighedstest. Se dine resultater i den vedhæftede PDF.';
}

// Create an array of headers
if($lang == 'english'){
 $headers = array(
   'Content-Type: text/html; charset=UTF-8',
   'From: "Artlinco Personality test" <mail@artlinco.com>',
);
}else{
 $headers = array(
   'Content-Type: text/html; charset=UTF-8',
   'From: "Artlinco Personlighedstest" <mail@artlinco.com>',
);
}      

//Check if the PDF file exists
if (file_exists($pdf_path)) {
   // Add the PDF file as an attachment
   $attachments = array($pdf_path);

   // Send the email with the PDF attachment
   $mail_sent = wp_mail($to, $subject, $body, $headers, $attachments);

   if ($mail_sent) {
       if($lang == 'english'){
           echo 'Email sent successfully with PDF attachment.<br> Please note, this mail might end up in your spam folder. Please check your spam folder for your results.';
       }else{
           echo 'E-mail blev sendt med PDF-vedhæftet fil.<br> Bemærk, at den tilsendte mail muligvis kan ende i din spamfolder. Tjek derfor din spamfolder for mail med dine resultater.';
       }
       
     
   } else {
       if($lang == 'english'){
            echo 'Email sending failed.';
       }else{
           echo 'Afsendelse af e-mail mislykkedes.';
       }
     
   }
} else {
   echo 'PDF file not found.';
}

   }
}

**Comment by tomasr78** [comment]
Please format the code and provide a readable error.

**Comment by marcelscholte** [comment]
Same issue here. Due to https://php.watch/versions/8.2/dynamic-properties-deprecated
I think that ConvertAPI has to review en change the affected classes to be compatible with php 8.2 or greater.
Then update Github with new version so I can update the APi by Composer.

**Comment by laurynas-baltsoft** [comment]
Fixed in 2.0.0 version:
https://github.com/ConvertAPI/convertapi-php/releases/tag/v2.0.0
