### ISSUE TITLE
PDF Content Issue

### ISSUE THREAD

**Issue by indiasan** [ConvertAPI/convertapi-php#54]
Hello,

I'm encountering an issue while converting HTML to PDF. I'm passing an HTML file with the content "Hello Test. How are you...?" but the generated PDF contains the content "7b Hello Sandeep. How are you...? 0". I've attached PDF file for your review.

Could you please assist me in identifying the issue as soon as possible?

Thank you.
[test2.pdf](https://github.com/ConvertAPI/convertapi-php/files/15046859/test2.pdf)

**Comment by tomasr78** [comment]
This question is not related to library itself but rather to API, please send your HTML file with description to our support e-mail or open chat on our web site.
