### ISSUE TITLE
Add possibility authenticate by token

### ISSUE THREAD

**Issue by paulius-petkus** [ConvertAPI/convertapi-php#58]
Currently library does not have ability to authenticate by **Access token:**

![image](https://github.com/user-attachments/assets/0e52b51f-9bdc-4098-9160-ff7b9078223f)

User can only authenticate with secret:
![image](https://github.com/user-attachments/assets/d041c8f7-73f5-476f-8cca-30a1e8fa79cf)

Need to add support for **access tokens** and an example would be great, too.

**Comment by tomasr78** [comment]
Not relevant anymore
